package frc.robot.Subsystem;


import edu.wpi.first.wpilibj2.command.SubsystemBase;



import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.TalonSRX;
import com.ctre.phoenix.motorcontrol.can.VictorSPX;


public class DriveTrain extends SubsystemBase
{
    private TalonSRX leftFront;
    private VictorSPX leftBack;
    
    private TalonSRX rightFront;
    private VictorSPX rightBack;

    public DriveTrain() 
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        leftFront = new TalonSRX(4);  //master 
        leftBack = new VictorSPX(1); //slave
        
        leftFront.configFactoryDefault();
        leftBack.configFactoryDefault();
        
        leftBack.follow(leftFront);  //assinging a slave to master

        rightFront = new TalonSRX(6); //master
        rightBack = new VictorSPX(3);  //slave

        rightFront.configFactoryDefault();
        rightBack.configFactoryDefault();
        
        rightBack.follow(rightFront);  //assigning a slave to master

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    public void driveVoltage(double x, double y)
    {
        double speed = x + y;           //sets the speed of the left wheels
        double speed1 = x - y;          //sets the speed of the right wheels

        leftFront.set(ControlMode.PercentOutput, speed);        //sets the LeftMaster to speed
        
        rightFront.set(ControlMode.PercentOutput, -speed1);     //sets the RightMaster to speed1
        
    }
}