package frc.robot.Subsystem;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DoubleSolenoid;

public class Triangle extends SubsystemBase
{

    private DoubleSolenoid doubleSolenoid1;

    public Triangle() 
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        doubleSolenoid1 = new DoubleSolenoid(0, 7, 0);                  //it declares the doubleSolenoid in PCM port 0, forward channel 7, backward channel 0
        addChild("Double Solenoid 1",doubleSolenoid1);                  //it adds a child
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    public void upT()
    {
        doubleSolenoid1.set(Value.kReverse);                                //it sets the triangle to up using the reverse channel
    }

    public void downT()
    {
        doubleSolenoid1.set(Value.kForward);                                //it sets the triangle to down using the forward channel
    }

    public void off()
    {
        doubleSolenoid1.set(Value.kOff);                                    //it turns of the triangle
    }

}
